# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    autofix_commit_msg: |
        chore(pre-commit): auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
            exclude: CHANGELOG.md
          - id: end-of-file-fixer
            exclude: CHANGELOG.md
          - id: check-yaml
            exclude: CHANGELOG.md
          - id: check-added-large-files
            exclude: CHANGELOG.md
          - id: check-json
          - id: pretty-format-json
          - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: '6e24ff01ab7d5e64045599b81c4cd34d6a6a7159'
      hooks:
          - id: prettier
