# https://medium.com/swlh/how-to-deploy-your-application-to-digital-ocean-using-github-actions-and-save-up-on-ci-cd-costs-74b7315facc2
name: Build & Deploy
on:
    release:
        types: [created, edited]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{ secrets.SSH_USERNAME }}

                  script: |
                      cd ~/doob
                      git pull
                      pm2 restart doob3
                      echo 'Deployment Complete'
