name: Run TSC
# Sourced from github.com/MrAuro
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    tsc:
        name: tsc
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: install node v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: yarn install
              run: yarn install
            - name: tsc
              uses: icrawl/action-tsc@v1
